$songs = [
    "10cc - Donna",
    "10cc - Dreadlock Holiday",
    "10cc - Good Morning Judge",
    "10cc - Rubber Bullets",
    "10cc - The Things We Do For Love",
    "10cc - the Wall Street Shuffle",
    "A ha - Take on Me",
    "ABBA - Chiquitita",
    "ABBA - Dancing Queen",
    "ABBA - Gimme! Gimme! Gimme!",
    "ABBA - The Day Before You Came",
    "ABBA - Waterloo",
    "Aaron Goodvin - Lonely Drum - country",
    "Abba - Mamma Mia",
    "Adamo - Vous permettez, monsieur",
    "Addy Kleijngeld - Accordeon medley - ACCORDEON",
    "Addy Kleijngeld - Schön ist die liebe im hafen - ACCORDEON",
    "After All - If You Need Me",
    "Al Bano & Romina Power - Sempre Sempre",
    "Alan Jackson - Chattahoochee - country",
    "Alan Jackson - Country Boy - country",
    "Alan Jackson - Livin On Love - country",
    "Alan Jackson - Remember When - country",
    "Alan Jackson - Small Town Southern Man - country",
    "Alanna Quinn - Other Side Of The Hill - country",
    "Albert Hammond - I Don t Wanna Die In An Air Disaster",
    "Albert Hammond - It never rains in Southern California",
    "Albert Hammond - The free Electric band",
    "Albert West & Shuffles - Sha la la i need you - 1970",
    "Albert West & The Shuffles - Bitter Tears - 1970",
    "Albert West & The Shuffles - Madelein - 1969",
    "Albert West & Tony Christie - Is this the way to Amarill",
    "Albert West &The Shuffles - Teardrop On Teardrop - 1970",
    "Albert West - Don t Say You Leave This Summer",
    "Albert West - For the Good Times",
    "Albert West - Ginny Come Lately",
    "Albert West - Put Your Head On My Shoulder",
    "Albert West - The Shuffles - Bitter Tears - 1970",
    "Albert West - You And Me",
    "Alice Kristiansen - Moon and Back - To The Moon & Back - country",
    "Alicia Kao - Qi Shi Ni Bu Dong Wo De Xi",
    "America - Sister Golden Hair",
    "Amy Macdonald - This Is The Life - Singing The Song - country",
    "Andre Hazes - Zeg maar niets meer",
    "Andre Hazes Jr - ik leef mijn leven",
    "Andre Moss - Ella",
    "Andre Moss - My Spanish Rose",
    "Andre Moss - Rosita",
    "Andrea Berg - Du hast mich tausendmal belogen",
    "Andrea Berg - Seemann, deine Heimat ist das Meer",
    "Andrea Jürgens - Amore, Amore",
    "Andrea Jürgens - Eleni hieß das Mädchen",
    "Andrea Jürgens - Manuel Goodbye",
    "Andrea Jürgens - Vaya Con Dios",
    "Andy Grammer - 85 - Almost 85 - country",
    "Andy Williams - Battle Hymn Of The Republic",
    "Angelina - Daan goon de lempkes aon",
    "Angelina - Dans met miech tot Morregevreug",
    "Animals - Don t Let Me Be Misunderstood",
    "Animals - The House of the Rising Sun",
    "Animals - We Gotta Get out of This Place",
    "Ann Tayler - Home to Louisiana - Louisiana Swing - country",
    "Ann Tayler - I Love You Because - I Love You Because - country",
    "Ann Tayler - Let Your Momma Go - Go Mama Go - country",
    "Anne Murray - MuSomebodys Always Saving Goodbye - country",
    "Anthony - Hou me vast",
    "Anthony Fokkema - Dans toch met mij - tango",
    "Antonia aus Tirol - 1000 Traume weit (Tornero)",
    "Aphrodite s Child - I Want To Live - Demis Roussos",
    "Aphrodite s Child - It s Five O Clock - Demis Roussos",
    "Aphrodite s Child - Rain and Tears - Demis Roussos",
    "Aquarius - The Sunshine In",
    "Archies - Sugar Sugar",
    "Arne Jansen - Meisjes Met Rode Haren",
    "Arne Lamberth And His Orchestra - A woman in love",
    "Art Garfunkel - Bright Eyes",
    "Ashley McBryde - Martha Divine - country",
    "Audry Landers - Manuel Goodby",
    "B J Thomas - Hooked on a Feeling",
    "BJ Thomas - Raindrops Keep Fallin On My Head - slow fox",
    "BJ Thomas - Whatever Happened to Old Fashioned Love",
    "BZN - Besame Mucho",
    "BZN - Countrymedley",
    "BZN - Don t say goodbye",
    "BZN - Mon Amour",
    "Backstreet Boys - As Long As You Love Me",
    "Backstreet Boys - I Want It That Way",
    "Barbados - Veronica - My Veronica - country",
    "Barbra Streisand - Second Hand Rose",
    "Barry Mcguire - Eve Of Destruction",
    "Beach Boys - God Only Knows",
    "Beach Boys - Good Vibrations",
    "Beach Boys - Sloop John B",
    "Beatles - A Hard Day s Night",
    "Beatles - All You Need Is Love",
    "Beatles - Can t Buy Me Love",
    "Beatles - Eleanor Rigby",
    "Beatles - Hello, Goodbye",
    "Beatles - Hey Jude",
    "Beatles - I Feel Fine",
    "Beatles - I Want To Hold Your Hand",
    "Beatles - In My Life",
    "Beatles - Michelle",
    "Beatles - No Reply",
    "Beatles - Penny Lane",
    "Beatles - Rock And Roll Music",
    "Beatles - Ticket To Ride",
    "Beatles - We Can Work it Out",
    "Beatles - Yellow Submarine",
    "Beatles - Yesterday",
    "Bee Gees - How Deep Is Your Love",
    "Bee Gees - I started A Joke",
    "Bee Gees - Jive Talkin",
    "Bee Gees - Massachusetts",
    "Bee Gees - Spicks Specks",
    "Bee Gees - Stayin Alive",
    "Bee Gees - To Love Somebody",
    "Bee Gees - Too Much Heaven",
    "Bee Gees - Words",
    "Bellamy Brothers - Feel Free",
    "Bellamy Brothers - Feelin the Feelin",
    "Bellamy Brothers - If I Said You Had A Beautiful Body",
    "Bellamy Brothers - Let Your Love Flow",
    "Bellamy Brothers - Vertical Expression (of Horizontal Desire) - country",
    "Bellamy Brothers - Vertical Expression",
    "Bellamy Brothers Ft John Anderson - No Country Music For Old Men - country",
    "Bellamy brothers - Lovers Live Longer",
    "Bellamy brothers - Sugar Daddy",
    "Belle Perez - Amame - country",
    "Belle Perez - El Mundo Bailando",
    "Belle Perez - Enamorada",
    "Belle Perez - Que Viva La Vida",
    "Belle Perez - Rebelde Amor - Rebel Amor - country",
    "Best Adventure - Leaving Thomas - Adventure 45 - country",
    "Bette Midler - The Rose",
    "Bigfoot - El Camino - El Camino - country",
    "Billie Jo Spears - Blanket on the Ground",
    "Billie Jo Spears - Marty Gray - country",
    "Billy J. Kramer And The Dakotas -  Do You Want To Know A Secret",
    "Billy Jo Spears - Sing me an old fashioned song",
    "Billy Joel - Piano Man",
    "Billy Joel - The River Of Dreams",
    "Billy Ray Cyrus - Achy Breaky Heart - Electric Slide - country",
    "Billy Swan - I Can Help",
    "Black Sabbath - Paranoid",
    "Blake Shelton - Corn - country",
    "Bobby Darin - 18 Yellow Roses",
    "Bobby Darin - Dream Lover",
    "Bobby Darin - Early In The Morning",
    "Bobby Darin - I ll Be There",
    "Bobby Darin - Mack The Knife",
    "Bobby Darin - Queen Of The Hop",
    "Bobby Darin - Splish Splash",
    "Bobby Darin - Treat My Baby Good",
    "Bobby Darin - You re The Reason I m Living",
    "Bobby Prins -  Adam En Eva",
    "Bobby Prins - 18 Yellow Roses",
    "Bobby Prins - Als Bloemen Konden Praten",
    "Bobby Prins - Dans nog eenmaal met mij",
    "Bobby Prins - De Jongen Met De Mondharmonica",
    "Bobby Prins - Een gitaar in de nacht",
    "Bobby Prins - Forever and ever",
    "Bobby Prins - Het maakt niets uit",
    "Bobby Prins - Ik bewonder jou",
    "Bobby Prins - Kristalwals",
    "Bobby Prins - La vie en rose",
    "Bobby Prins - Marinairo",
    "Bobby Prins - Pallieterwals",
    "Bobby Prins - Twee Bloedrode Rozen",
    "Bobby Prins - Waarheen",
    "Bobby Prins - toe kom in mein armen",
    "Bobby Vinton - Blue Moon",
    "Bobby Vinton - Blue On Blue",
    "Bobby Vinton - Blue Velvet",
    "Bobby Vinton - Hurt",
    "Bobby Vinton - Let s Kiss and Make Up",
    "Bobby Vinton - Mr Lonely",
    "Bobby Vinton - My Melody Of Love",
    "Bobby Vinton - My Special Angel",
    "Bobby Vinton - Please Love Me Forever",
    "Bobby Vinton - Roses Are Red",
    "Bobby Vinton - Sealed with a Kiss",
    "Bobby Vinton - To Know You Is To Love You",
    "Bobby prins - Een koffer vol met drome",
    "Boney M - Daddy Cool - Cooler Then Cool - country",
    "Boney M - Ma Baker",
    "Boney M - Rasputin",
    "Boney M - Rivers of Babylon",
    "Boudewijn de Groot - Land van Maas en Waal",
    "Bouke - A Love Worth Waiting For",
    "Bouke - A Song Of Love",
    "Bouke - Bella Bella Donna",
    "Bouke - Blame It On The Summersun",
    "Bouke - Bridge Over Troubled Water",
    "Bouke - Calypso Mexico - Calypso Maxico - country",
    "Bouke - Calypso Mexico",
    "Bouke - Dans De Hele Nacht Met Mij",
    "Bouke - Denise",
    "Bouke - For The Good Times",
    "Bouke - Hear My Song - Hear My Song - country",
    "Bouke - Hear My Song",
    "Bouke - Hot Sexy Mama - Hot Sexy Mama - country",
    "Bouke - Hot Sexy Mama",
    "Bouke - Hurt",
    "Bouke - I Cry",
    "Bouke - If You Need Me",
    "Bouke - Ik Hoor Mooie Muziek",
    "Bouke - In Mijn Hart Ben Jij Bij Mij",
    "Bouke - Jane",
    "Bouke - Kijk Me Toch Eens Aan",
    "Bouke - Lady In Blue",
    "Bouke - Lets Dance",
    "Bouke - Lonely Lady - Lonely Lady - country",
    "Bouke - Lonely Lady",
    "Bouke - Love Hurts",
    "Bouke - Maria Magdalena",
    "Bouke - Marina",
    "Bouke - Mister Lonely",
    "Bouke - Monica",
    "Bouke - Only Make Believe",
    "Bouke - Seven Lonely Days",
    "Bouke - She Wears My Ring",
    "Bouke - Sinds Jij Bij Me Bent",
    "Bouke - Spanish Eyes",
    "Bouke - Suzy, Ik Mis Je",
    "Bouke - Tonight Is Allright For Love",
    "Bouke - We Walk In The Sunshine",
    "Bouke - You (DU)",
    "Bouke - You re My World",
    "Bouke - Zeven Dagen, Zeven Nachten",
    "Box Tops - The Letter",
    "Boyzone - No Matter What",
    "Brad Paisley - I ve Been Better - country",
    "Brian Hyland - Ginny come lately",
    "Brooke Fraser - Something In The Water - Something in The Water - country",
    "Brooks & Dunn - Boot Scootig Boogie - country",
    "Brooks & Dunn - Neon Moon (Remix) - Sun goes down on my side of tow - country - line dance",
    "Brooks and Dunn - Boot Scootig Boogie - country",
    "Bruce Springsteen - Dancing in the Dark",
    "Buoys - Give Up Your Guns",
    "Byrds - Mr Tambourine Man",
    "CLIFF RICHARD - CONGRATULATIONS 1968",
    "Calimeros - Monja",
    "Canyon - Mooi volendam",
    "Captain Cook - Fremdenlegionar Saxophone",
    "Captain Cook - Patrona Bavaria",
    "Captain Cook - Sail Along Silvery Moon",
    "Carl Douglas - Kung Fu Fighting",
    "Carline Carter - Every Little Thing",
    "Cascades - Dreamin",
    "Cascades - First Love Never Dies",
    "Cascades - Rhythm of the Falling Rain",
    "Catharine Hulte - Bel me op als je eenzaam bent",
    "Cats - I Gotta Know Wha",
    "Cats - Jukebox",
    "Cats - Lea",
    "Cats - Marian",
    "Cats - One Way Wind",
    "Cats - Save The Last Dance",
    "Cats - Scarlet Ribbons",
    "Cats - Where Have I Been Wrong",
    "Cats - Why",
    "Celine Dion - I m Alive",
    "Charelle & Franky Falcon - Blijf Bij Mij",
    "Charles Aznavour - She",
    "Charlie Landsborough - Close Your Eyes",
    "Charlie Landsborough - Heaven Knows",
    "Charlie Landsborough - I Want Someone Who Will Love Me",
    "Charlie Landsborough - I Will Love You All My Life",
    "Charlie Landsborough - Love you every second",
    "Charlie Landsborough - My Forever Friend",
    "Charlie Landsborough - No Time at All",
    "Charlie Landsborough - One Day At A Time",
    "Charlie Landsborough - Part of Me",
    "Charlie Landsborough - The Isle of Innisfree",
    "Charlie Landsborough - What colour is the wind",
    "Charlie Rich - The Most Beautiful Girl",
    "Chicago - If You Leave Me Now",
    "Chris Andrews - To Whom It Concerns",
    "Chris Andrews - Yesterday Man",
    "Chris Isaak - It s Now or Never - Be Mine Tonight - country",
    "Chris Janson - Everybody - Every Bady Wanna - country",
    "Chris Norman & Suzi Quatro - Stumblin In 1978",
    "Chubby Checker - Lovely lovely",
    "Cliff Richard - Living Doll",
    "Cliff Richard - Lucky Lips",
    "Cliff Richard - Summer Holiday",
    "Cliff Richard - The Young Ones",
    "Cliff Richard - We Don t Talk Anymore",
    "Cliona Hagan - Keepin Cool Company - country",
    "Collin Ray - April Fool - country",
    "Corrie en de Rekels - Huilen is voor jou te laat",
    "Corrie en de Rekels - Ik Hoor Nog Je Stem",
    "Corrie en de Rekels - Rozen Die Bloeien",
    "Corry - Ik Krijg Een Heel Apart Gevoel Van Binnen",
    "Corry En De Rekels - Jukebox",
    "Corry Konings - Mooi Was Die Tijd",
    "Corry en de Rekels - Adio, Adio, Adio",
    "Corry en de Rekels - Zonder t Te Weten",
    "Country Crusaders - Triple Mix - Triple Mix - country",
    "Country Sisters - Let s twist again",
    "Cowboy Gerard - Het spel kaarten",
    "Credence - Have you ever seen the rain",
    "Creedence Clearwater Revival - Bad Moon Rising",
    "Creedence Clearwater Revival - Green River",
    "Creedence Clearwater Revival - Have You Ever Seen The Rain",
    "Creedence Clearwater Revival - I Put a Spell on You",
    "Crew Cuts - Sh Boom Sh Boom",
    "Crispian St Peters - Almost Persuaded",
    "Crispian St Peters - You Were On My Mind",
    "Crispian St. Peters - The Pied Piper",
    "Crystals - Then He Kissed Me",
    "Cuby & The Blizzards - Window Of My Eyes",
    "Culture Club - Karma Chameleon",
    "DJ Berta - Amame",
    "Dalida - Gigi L amoroso",
    "Dana Winner - One Moment In Time live",
    "Dana Winner - One Way Win",
    "Daniel Boone - Beautiful Sunday",
    "Daniel O Donnel - Do You Wanna Danc",
    "Daniel O Donnel - I Just Want to Dance With Yo",
    "Daniel O Donnel - I Need You",
    "Daniel O Donnell - Heaven With You - Heaven With You - country",
    "Danny Everett - Indo Dreams - Indo Dreams - country",
    "Danny Vera - Roller Coaster",
    "Dave Berry - I M Gonna Take You There",
    "Dave Berry - Little Things",
    "Dave Berry - Now",
    "Dave Berry - This Strange Effect",
    "Dave Dee Dozey Beaky Mick Tich - Bend It",
    "Dave Dee Dozy Beaky Mick Tich - The Legend Of Xanadu",
    "Dave Dee, Dozy, Beaky, Mick And Tich - Zabadak",
    "Dave Sheriff - Cha Tango - Tango With The Sheriff - country",
    "Dave Sheriff - Red Hot Salsa - Red Hot Salsa - country",
    "David Civera - Que La Detengan - La Tenga - country",
    "David Garrick - Dear Mrs Applebee",
    "David Garrick - Lady Jane",
    "Dawn - Knock Three Times",
    "Dawn - Tie a Yellow Ribbon Round the Ole Oak Tree",
    "De Dixie Aces - She ll Have To Go",
    "De Heikrekels - Waarom Heb Jij Me Laten Staan",
    "De Zingende Amateur - Ouwe Orgelman",
    "Deep Purple - Child in Time",
    "Del Shannon - Runaway",
    "Demis Roussos - Goodbye My Love Goodby",
    "Demis Roussos - Perdoname - country",
    "Demis Roussos - Perdoname",
    "Den Gamle - Tennesse Waltz",
    "Derek Ryan - Better Times A Comin - Better Times - country",
    "Derek Ryan - Dancing In The Moonlight - Dancing In The Moonlight - country",
    "Derek Ryan - Firefly - Fireflies - country",
    "Derek Ryan - On The Sesh - country",
    "Dion - Runaround Sue",
    "Dire Straits - Brothers In Arms",
    "Dire Straits - Sultans Of Swing",
    "Dire Straits - Walk Of Life",
    "Dixie Aces - She ll Have To Go",
    "Dj Ice - Barbie Gir - slow fox",
    "Django Wagner & Theo van Cleeff - Amigos para siempre - rumba",
    "Django Wagner - Kali",
    "Django wagner - Diana, Ik denk aan jou",
    "Django wagner - Die mooie ogen",
    "Django wagner - I ll never gonna fall in love",
    "Django wagner - Ik Wil Bij Je Zij",
    "Django wagner - I´ll never gonna fall in love",
    "Django wagner - Mijn schatje",
    "Dolly Parton & Kenny Rogers - Islands In the Stream - country",
    "Dolly Parton - 9 to 5",
    "Dolly Parton - Backwoods Barbie - Backwoods Girl - country",
    "Don Omar - Danza Kuduro - Danza Kuduro - country",
    "Donny & Marie Osmond - I m Leaving It All Up To You",
    "Donovan - Atlantis",
    "Donovan - Mellow Yellow",
    "Donovan-Atlantis",
    "Doors - Riders on the storm",
    "Doris Day - Dream A Little Dream of Me",
    "Doris Day - Whatever Will Be, Will Be (Que Sera, Sera)",
    "Dr Hook - Sharing The Night Together",
    "Dr Hook - When You re In Love With A Beautiful Woman",
    "Dr Victor - If You Wanna Be Happy - Crazy Foot Mambo - country",
    "Drafi Deutscher - Marmor,Stein und Eisen bricht",
    "Duncan Laurence - Arcade - Arcade - country",
    "Duo Gerrie en Ron - I Guess - country",
    "Dwight Yoakam - Crazy Little Thing Called Love",
    "Dwight Yoakam - Guitars Cadillacs - country",
    "Dwight Yoakam - Guitars Cadillacs",
    "E Type - Banca Banca - Banca Cha - country",
    "Eagles - Desperado",
    "Eagles - Hotel California",
    "Eagles - Lyin Eyes",
    "Eagles - New Kid in Town",
    "Eagles - One of These Nights",
    "Eagles - Take It Easy",
    "Earth Fire - Memories",
    "Earth Fire - Weekend",
    "Earth, Wind  Fire - Boogie Wonderland",
    "Easybeats - Friday On My Mind",
    "Eddy Arnold - Cattle Call (Whisperin)",
    "Eddy Arnold - Make the World Go Away",
    "Eddy Raven & Jo-El Sonnier - Jambalaya - Jambalaya - country",
    "Eddy Raven - Island - country",
    "Eddy Wally - Als Marktkramer Ben Ik Geboren",
    "Eddy Wally - Cherie",
    "Eddy Wally - Dans n Tango Met Mij",
    "Eddy Wally - Met Gesloten Ogen",
    "Eden - You re My First Love - Love You A Million Times - country",
    "Ekseption - Air",
    "Electric Light Orchestra - Rock N Roll Is King",
    "Elton John - Blessed - Blessed - country",
    "Elvis Presley - Are You Lonesome Tonight",
    "Elvis Presley - Can t Help Falling In Love",
    "Elvis Presley - In the Ghetto",
    "Elvis Presley - It Hurts Me",
    "Elvis Presley - It s Now or Never",
    "Elvis Presley - Kiss Me Quick - Kiss Me Quick - country",
    "Elvis Presley - Love Me Tender",
    "Engelbert Humperdinck  - Quando Quando Quando - Quando When Quando - country",
    "Engelbert Humperdinck - A Man Without Love",
    "Engelbert Humperdinck - Can t Take My Eyes Off You",
    "Engelbert Humperdinck - Please Release Me (Let Me Go)",
    "Engelbert Humperdinck - Quando Quando Quando",
    "Engelbert Humperdinck - Spanish Eyes",
    "Engelbert Humperdinck - The Last Waltz - Shy Waltz - country",
    "Engelbert Humperdinck - The Last Waltz",
    "Enrique Iglesias  Feat Romeo Santos - Loco - country",
    "Enrique Iglesias - Duele el Corazon - Corazon - country",
    "Eric Church - Rock & Roll Found Me - country",
    "Esther and Abi Ofarim - Cinderella Rockefella",
    "Everly Brothers - All I Have to Do Is Dream",
    "Everly Brothers - Bye Bye Love",
    "Everly Brothers - Cathy s Clown",
    "Everly Brothers - Crying In The Rain",
    "Everly Brothers - Love Hurts",
    "Everly Brothers - On The Wings Of A Nightingale",
    "FRANK SINATRA - Strangers In The Night",
    "Fito Olivares - Fin De Semana - Cumbia Semana - country",
    "Fleetwood Mac - Albatross",
    "Fleetwood Mac - Dreams",
    "Fleetwood Mac - Go Your Own Way",
    "Fleetwood Mac - Little Lies",
    "Fleetwood Mac - Need Your Love So Bad",
    "Fortunes - Here It Comes Again",
    "Fortunes - You ve Got Your Troubles",
    "Foundations - Baby Now That I ve Found You",
    "Foundations - Build Me Up Buttercup",
    "Fox d antan - (Fox-trot)",
    "France Gall - Poupee de Cire Poupee de Son",
    "Frank Galan - El Bandido",
    "Frank Galan - Que Si, Que Si, Que No",
    "Frank Galan - ♡ TU ♡",
    "Frank Sinatra - Killing me softly",
    "Frank Sinatra-Killing me softly",
    "Frank Verkooyenhom - Wie wil er met mij dansen",
    "Frans Bauer - Als Sterren Aan De Hemel Staan",
    "Frans Bauer - Had Ik Maar Nooit Naar Jou Gekeken",
    "Frans Bauer - Jouw Hart Is Als Chocolade",
    "Frans Bauer - N Trein Naar Niemandsland",
    "Frans Duijts - Lieveling",
    "Frans Duyts - Jij Denkt Maar Dat Je Alles Mag Van Mij",
    "Franz Joostink - Dat Ben Jij",
    "Freddy Breck - Rote Rosen",
    "Freddy Breck - Uberall Auf Der Welt",
    "Freddy Fender - Before The Next Teardrop Falls",
    "Freddy Fender - Vaya Con Dios",
    "Freddy Fender - Wasted Days And Wasted Nights",
    "Freddy Fender - Wild Side Of Life",
    "Funky G ft Candi Stanton - Suspicious Minds - Suspicious Minds - country",
    "Gary P Nunn - Down To Louisiana - Down To Louisiana - country",
    "Gary Puckett & Union Gap - Young Girl",
    "Gary Puckett - Lady Willpower",
    "Gary Puckett - Silence Is Golden",
    "Gebroeders ko - Zonnebril",
    "Gente de Zona - Mas Macarena - (Cover Audio) ft Los Del Rio",
    "George Baker - Beautiful Rose",
    "George Baker Selection - Fly away litlle paraqauyo",
    "George Baker Selection - Little Green Bag",
    "George Baker Selection - Morning Sky",
    "George Baker Selection - Paloma Blanca",
    "George Harrison -  I ve Got My Mind Set On You",
    "George Harrison - My Sweet Lord",
    "George McCrae - Rock Your Baby",
    "George Michael - Careless Whisper - slow fox",
    "George Strait - The Big One - Big Love - country",
    "Gerard Cox - T Is Weer Voorbij Die Mooie Zomer",
    "Gerard Joling & Tino Martin - Laat Me Leven",
    "Gerard Joling - No More Bolero",
    "Gerrit Uittenberg - Mooi Raamsdonkveer",
    "Gerry & The Pacemakers - You ll Never Walk Alone",
    "Gerry The Pacemakers - Ferry Cross The Mersey",
    "Gerry and the Pacemakers - How do you do it",
    "Gerry the pacemakers - I like it",
    "Gery Puckett and the Union Gap - Young Girl",
    "Gipsy Kings - Habla Me",
    "Gipsy Kings - Volare",
    "Glen Campbell - By The Time I Get To Phoenix",
    "Glen Campbell - Gentle On My Mind",
    "Glen Campbell - Rhinestone Cowboy",
    "Glen Campbell - Try A Little Kindness",
    "Glen Campbell - Yesterday, When I Was Young",
    "Golden Earring - Back Home",
    "Golden Earrings - Please Go",
    "Golden Earrings - That Day",
    "Goombay Dance Band - Seven Tears",
    "Goombay Dance Band - Sun of Jamaica",
    "Graziono - Rot Sind Die Rosen",
    "Gudrun Jankis - Letkis",
    "Guys n Dolls - You re My World",
    "Hank Williams - Jambalaya On the Bayou",
    "Hanny en De Rekels - Mario",
    "Heartbreaker - Slow Fox",
    "Heather myles - Who Did You Call Darlin - country",
    "Heidi Hauge - It s A Cowboy Lovin Night",
    "Heidi Hauge - Save the Last Dance for My",
    "Heidi Hauge - Seven Spanish Angels",
    "Heidi Hauge - Some Broken Hearts Never Ment",
    "Heidi Hauge - Still Love You - country",
    "Heidi Hauge - Turn It On, Turn It Up, Turn Me Loos",
    "Heikrekels - Waarom Heb Jij Me Laten Staan",
    "Heintje - Ich Bau Dir Ein Schloss",
    "Helemaal Hollands - Wat is het leven zonder vrienden",
    "Helmondia Trio o.l.v. Addy Kleijngeld - Accordeon medley",
    "Henk Damen - Laat mij alleen",
    "Henk Damen - Twee Lieve Armen Om Me Heen",
    "Henk Damen Zangeres Zonder Naam - Jongen",
    "Hermans Hermits - No Milk Today",
    "Hermans Hermits - Theres a Kind of Hush",
    "High Way - Shake Hands",
    "Highway - Crazy love",
    "Highway - Je Hoeft Niet Mooi Te Wezen",
    "Highway - Kiddy, kiddy kiss me",
    "Highway - Voor Sonja Doe ik alles",
    "Hollies - Bus Stop",
    "Hollies - Long Cool Woman",
    "Hollies - Sorry Suzanne",
    "Hollies - The Air That I Breathe",
    "Hot Butter - Popcorn",
    "I Santo California - Tornero",
    "Ireen Sheer - Tennessee Waltz - Tennessee Waltz Surprise - country",
    "Jack Jersey - Blue brown eyed lady",
    "Jack Jersey - In The Still Of The Night",
    "Jack Jersey - Lonely Me",
    "Jack Jersey - Papa was a Poor Man",
    "Jack Jersey - You re Not Gonna See Me Cryin",
    "James Brown - Its A Mans Mans Mans World",
    "James hype - More than friends - No Strings Attached - country",
    "Jamie O Neal - Just One Time - Makita - country",
    "Jane Birkin et Serge Gainsbourg - Je Taime,...Moi Non Plus",
    "Jane McDonald - Blame It on the Bossa Nova - country",
    "Jason Allen - Elvis Tonight - Wanna Be Elvis - country",
    "Jay & The Americans - Cara Mia",
    "Jay & The Americans - Come A Little Bit Closer",
    "Jeff Beck and the Big Town Playboys - Lotta Lovin - country",
    "Jewel Akens - The Birds and the Bees",
    "Jewel Akens-The Birds and the Bees",
    "Jill King - Can t Let go - country",
    "Jim Croce - Time in a bottle 1973",
    "Jim Reeves - Distant Drums",
    "Jim Reeves - I Love You Because",
    "Jim Reeves - Put Your Sweet Lips a Little Closer",
    "Jim Reeves - Roses are red my love",
    "Jimmy Fortune - Far Side Banks Of Jordan - country",
    "Joe Dolan - Good looking woman",
    "Joe Dolan - Lady In Blue",
    "Joe Dolan - Make Me An Island",
    "Joe Dolan - You re Such a Good Looking Woman",
    "Joe Merrick - Yolanda - Yolanda - country",
    "John And Yoko - The Ballad Of John And Yoko",
    "John Denver - Annie s Song",
    "John Denver - Calypso",
    "John Denver - Leaving On A Jet Plane",
    "John Denver - Rocky Mountain High",
    "John Denver - Take Me Home, Country Roads",
    "John Fogerty - Blue Moon Nights - Blue Moon Shuffle - country",
    "John Fogerty - Don t You Wish It Was True - Don t You Wish - country",
    "John Lennen - Imagine",
    "John Mayer - In The Blood - In The Blood - country",
    "John Travolta & Olivia Newton John - the grease",
    "John Woodhouse - Melodia",
    "John de Bever - Als een Hemel zonder SterrenLicht",
    "John de Bever - Bolero Medley - rumba",
    "John de Bever - Dans Tot De Morgen - Rumba",
    "John de Bever - Ga Je Weg",
    "John de Bever - Hartendief",
    "John de Bever - Huil Maar Niet Meer",
    "John de Bever - Kleine leugenaar",
    "John de Bever - Kom Eens Dicht Bij Mij",
    "John de Bever - Kom Terug",
    "John de Bever - Laat Ons Dansen",
    "John de Bever - Net Als Vroeger",
    "John de Bever - Waarom Waarom Waarom",
    "John de Bever - Zaterdag",
    "Johnny & Rijk - De Bostella",
    "Johnny Gold - Jou herken ik",
    "Johnny Lion - Sophietje",
    "Jolie Holliday - Shy Little Bayou Love - Shy Little Bayou Love - country",
    "Jonathan King - Hooked On A Feeling",
    "Juan Gabriel - Cosas De Enamorados",
    "Juan Gabriel - Es Mejor",
    "Juan Gabriel - Insencible",
    "Juan Gabriel - No Me Vuelvo a Enamorar - rumba",
    "Juan Gabriel - Noche a Noche",
    "Juan Gabriel - Si Quieres - rumba",
    "Juan Gabriel - Tu Me Dijiste Adios",
    "Juan Gabriel - Un Amor",
    "Juan Gabriel - Ya Lo Se Que Te Vas",
    "Juan Magan - He Llorado (Como Un Niño) - country",
    "Juan gabriel - Una Vez Mas",
    "Julio Iglegias - Hey",
    "Julio Iglegias - Manuela",
    "Julio Iglegias - Me Olvide De Vivi",
    "Julio Iglesias - Abrazame",
    "Julio Iglesias - Amor , Amor , Amor",
    "Julio Iglesias - El Bacalao - El Bacalao - country",
    "Julio Iglesias - El Bacalao",
    "Julio Iglesias - Me olvidé de vivir",
    "Julio Iglesias - Moralito",
    "Julio Iglesias - Quiereme Mucho",
    "Julio Iglesias - Un canto a Galicia",
    "Julio Iglesias - tango",
    "Julio iglesias - 33 años",
    "Julio iglesias - Quiero",
    "Justin Timberlake - Can t Stop The Feeling - So Just Dance Dance Dance - country",
    "Kaoma - Lambada 1989",
    "Kenny Chesney - When I Close My Eyes",
    "Kevin Deal - In the Wind - country",
    "Kinks - Dedicated Follower of Fashion",
    "Kinks - Sunny Afternoon",
    "Kinks - Waterloo Sunset",
    "Kiss - i was made for loving you",
    "Koos Alberts - Ik Verscheurde Je Foto",
    "Koos Alberts - Zijn Het Je Ogen",
    "Kumbia All Starz - Speedy Gonzales - Speedy Gonzales - country",
    "LUV - Youre The Greatest Lover",
    "Laura Pausini - Surrender - Surrender - country",
    "Leonard Cohen - Dance me to the end of love",
    "Les Humphries Singers - Mexico",
    "Les Humphries Singers - To my father s house",
    "Leslie Grace - Be My Baby - Be My Baby Now - country",
    "Leslie Grace - Be My Baby - country",
    "Lewis Capaldi - Someone You Loved - Into Nigthfall - country",
    "Little Eva - Locomotion",
    "Little Richard - Tutti Frutti",
    "Locomotion - ",
    "Locomotions - Cliff Richard medley",
    "Locomotions - Everynight",
    "Long Tall Ernie The Shakers - Do You Remember",
    "Los Lobos Gipsy Kings - La Bamba",
    "Los Pop Tops - Mamy Blue",
    "Los del Rio - Macarena",
    "Lou Bega - Angelina",
    "Louis Armstrong - What a Wonderful World",
    "Luc Steeno - hij speelde accordeon",
    "Luc steeno - Dan gaan de lichtjes aan",
    "Lucille Starr - Crazy Arms (1964)",
    "Lucille Starr - The French Song (1965)",
    "Luis Fonsi & Demi Lovato - Echame La Culpa - country",
    "Lynn Anderson - For the Good Times",
    "Lynn Anderson - Rose Garden",
    "Lynn Anderson - You re My Man",
    "Lynsey De Paul - Sugar Me 1972",
    "MARBLES - ONLY ONE WOMEN",
    "Madison CowBoy - Last Night - country",
    "Mamas en The Papas - California Dreamin",
    "Mamas en The Papas - Monday Monday",
    "Manfred Mann - Do Wah Diddy Diddy",
    "Manfred Mann - Ha Ha Said The Clown",
    "Manfred Mann - The Mighty Quinn",
    "Manhattans - Kiss and Say Goodbye",
    "Marianne Faithfull - As Tears Go By",
    "Marianne Faithfull - Summer Nights",
    "Marianne Weber & John De Bever - Dat Is De Liefde",
    "Marianne Weber - De Italiaan",
    "Marianne Weber - Ik Weet Dat Er Een Ander Is",
    "Marianne Weber - Schrijf Me Nooit Geen Mooie Brieven",
    "Marie Osmond - Paper Roses",
    "Mark Knopfler & Emmylou Harris - Love and Happiness - Love and Happiness - country",
    "Marty Haggard - Mams Hungry Eyes - country",
    "Marty Robbins - El Paso",
    "Marty Robbins - Teenage Drea",
    "Master KG ft Nomcebo - Jerusalema - Jerusalema - country",
    "Mavericks - All You Ever Do Is Bring Me Down",
    "Mavericks - Dance The Night Away",
    "Mavericks - La Mucara",
    "Meghan Trainor - Goosebumps - Goosebumps - country",
    "Merrymen - Big bamboo",
    "Michael Jackson - Billie Jean",
    "Middle Of The Road - Sacramento",
    "Midland - Runnin Wild - country",
    "Mighty Sparrow Byron Lee - Only A Fool",
    "Miguel Moly - Mamita Mia",
    "Miriam Makeba - Pata Pata - Hi A Ma Cha - country",
    "Modern Talking - No Face, No Name, No Number",
    "Monkees - Daydream Believer",
    "Moody Blues - I m Just A Singer",
    "Moody Blues - Nights In White Satin",
    "Moody Blues - Tuesday Afternoon",
    "Moonlights - Wals met maria",
    "Moonshine Man - Trouble - My Middle Name - country",
    "Motions - It s The Same Old Song",
    "Motions - Wasted Words",
    "Motions - Why Don t You Take It",
    "Mouth and MacNeal - How do you do",
    "Mud - Dynamite",
    "Mud - Tiger Feet",
    "Mungo Jerry - In the summertime",
    "Mystic - Ritmo De La Noche (Sunburst Mix)",
    "Mystic - Ritmo de la noche",
    "NINI ROSSO - IL SILENZIO 1964",
    "Nathan Carter - Good Time Girls - Good Time Girls - country",
    "Nathan Carter - You Got Gold - country",
    "Nazareth - Love Hurts",
    "Neil Diamond - I am I said",
    "Neil Diamond - Sweet Caroline",
    "Neil Sedaka - Breaking Up Is Hard to Do",
    "Neil Sedaka - Calendar Girl",
    "Neil Sedaka - Happy Birthday, Sweet Sixteen",
    "Neil Sedaka - Laughter In The Rain",
    "Neil Sedaka - One Way Ticket",
    "Neil sedaka - Oh Carol",
    "Niamh Lynn - Got a Lotta Rhythym In My Soul",
    "Niamh Lynn - Sing Me an Old Fashioned Song",
    "Niamh Lynn - While I was Making Love To You",
    "Nick Mackenzie - Hello Good Morning",
    "Nick Mackenzie - Juanita",
    "Nick Mackenzie - One Is One",
    "Nico Haak - Foxie Foxtrot",
    "Nicoletta - Mamy Blue [1971]",
    "Nina Simone - Ain t Got No, I Got Life",
    "Nina Simone-Ain t Got No, I Got Life",
    "Nino de Angelo - Back Again(Tornero) - line-dance",
    "OMI - Babylon - Babylon - country",
    "OMI - Cheerleader - Cheerio - country",
    "Olivia Newton John - Hopelessly Devoted to You",
    "Op Een Mooie Pinksterdag - Leen Jongewaard",
    "Orchestra Mario Riccardi - Caballero - country",
    "Orchestra Mario Riccardi - Cuore ballerino - Dancing Heart - country",
    "Oscar Harris - Since I Met You Baby",
    "Oscar Harris and the Twinkle Stars - Soldier s prayer",
    "Oscar Harris and the Twinkle Stars - Try a Little Love",
    "Osmonds - Crazy Horses",
    "Otis Redding - I Got Dreams To Remember",
    "Otis Redding - Sittin On The Dock Of The Bay",
    "Outsiders - Lying All The Time",
    "Overtones - Breaking up Is Hard to Do",
    "Overtones - Do You Love Me",
    "Overtones - Love Really Hurts Without Yo",
    "Overtones - Pretty Woma",
    "Overtones - Runaround Su",
    "Overtones - Runawa",
    "Overtones - Runaway",
    "Overtones - Saturday Night at the Movie",
    "Overtones - Teenager in Love",
    "Overtones - The Bare Necessities  I Wanna Be Like Yo",
    "Overtones - Who Put the Bomp",
    "PERCY SLEDGE - MY SPECIAL PRAYER - 1967",
    "POPPYS NON - NON RIEN N A CHANGE",
    "Partridge Family - I Think I Love You",
    "Paul Anka - Diana",
    "Paul McCartney Wings - Mull Of Kintyre",
    "Peret - Borriquito",
    "Perry Como - Killing Me Softly with Her Song",
    "Peter And Gordon - A World Without Love",
    "Peter Maffay - Du",
    "Peter Paul & Mary - Early Morning Rain - (1966)",
    "Peter Sarstedt - Where Do You Go To My Lovely",
    "Peter and Gordon -  Woman",
    "Peter and Gordon - Five Hundred Miles",
    "Peter and Gordon - I Go to Pieces",
    "Peter, Paul & Mary - Lemon Tree",
    "Petula Clark - Chariot - I Will Follow Him",
    "Petula Clark - Don t Sleep in The Subway",
    "Petula Clark - Downtown",
    "Petula Clark - My love is warmer than the sunshine",
    "Petula Clark - This Is My Song",
    "Petula Clark - You re The One",
    "Piet Veerman - Ticket To Heaven - cats",
    "Piet Veerman - You d better move on - Can t Let Go - country",
    "Platters - Only You",
    "Platters - Twilight Time",
    "Platters - You ll Never Know",
    "Pop Tops - Mamy Blue",
    "Power Music Workout - Islands in the Stream - Islands in The Stream - country",
    "Procol Harum - A Whiter Shade Of Pale",
    "Procol_Harum - Homburg",
    "Procol_Harum-Homburg",
    "Pussycat - Georgie",
    "Pussycat - Mississippi",
    "Pussycat - My Broken Souvenirs",
    "Pussycat - Smile",
    "Pussycat - Teenage Queenie",
    "Queen - Bohemian Rhapsody",
    "Queen - Somebody To Love",
    "Queen - We Are The Champions",
    "ROBERTA FLACK - KILLING ME SOFTLY",
    "Racey - Lay Your Love On Me",
    "Radar Love - Golden Earring",
    "Ramses Shaffy - Sammy 1966",
    "Raul Malo - I Said I Love You - country",
    "Ray Charles - Georgia On My Mind",
    "Redbone - We Were All Wounded At Wounded Knee",
    "Richard Parker - My Island Lady - country",
    "Rick Astley - Never Gonna Give You Up",
    "Ricky King - Goodbye My Love Goodby",
    "Ricky King - Goodbye My Love Goodbye",
    "Ricky King - Rot sind die Rosen",
    "Ricky Martin - Livin La Vida Loca",
    "Ricky Martin - Un, Dos,Tres, Maria",
    "Ricky Nelson - Cindy",
    "Ricky Nelson - Dreamlover",
    "Ricky Nelson - Garden Party",
    "Ricky Nelson - Hello Mary Lou",
    "Ricky Nelson - I Will Follow You",
    "Ricky Nelson - Never Be Anyone Else But You",
    "Ricky Nelson - Poor Little Fool",
    "Ricky Nelson - Teenage Idol",
    "Ricky Nelson - Travellin Man",
    "Ricky Nelson - Unchained Melody",
    "Righteous Brothers - Unchained Melody",
    "Righteous Brothers - You ve Lost That Lovin Feelin",
    "Ritchie Valens - We Belong Together",
    "Robbie Williams & Nicole Kidman - Something Stupid",
    "Robert Pater - Helena",
    "Robert Strating - Maladie D Aamour",
    "Roberto Scaglioni - Fascination",
    "Robin Gibb - Saved By The Bell",
    "Robin Thicke - Blurred Lines - Blurred Lines - country",
    "Rocco Granata - Marina",
    "Rod Mckuen -  Soldiers who want to be heroes",
    "Rod Stewart - Maggie May",
    "Roger Whittaker - Schön war die Zeit",
    "Rolling Stones - (I Can t Get No) Satisfaction",
    "Rolling Stones - 19th Nervous Breakdown",
    "Rolling Stones - Honky Tonk Women",
    "Rolling Stones - Let s Spend The Night Together",
    "Rolling Stones - The Last Time",
    "Ronan Hardiman - Dance Above The Rainbow - country",
    "Ronan Hardiman - Lord Of The Dance - Riverdance - country",
    "Ronettes - Be My Baby",
    "Roy Orbison - California Blue - California Blue - country",
    "Roy Orbison - California Blue",
    "Roy Orbison - Goodnight",
    "Roy Orbison - In Dreams",
    "Roy Orbison - It s Over",
    "Roy Orbison - Oh, Pretty Woman",
    "Roy Orbison - Only The Lonely",
    "Roy Orbison - You Got It",
    "SCORPIONS - HELLO JOSEPHINE",
    "Saint Lanvain - If Jesus Loves Me ft Rahmsed - Groovy Love - country",
    "Sam The Sham & The Pharaohs - Wooly Bully",
    "Sandie Shaw - Those Were The Days (1968)",
    "Scooter Lee - I Still Believe - Believin - country",
    "Scorpions - Wind of Change",
    "Scott Fitzgerald Yvonne Keeley - If I Had Words",
    "Scott Mckenzie - San Francisco",
    "Searchers - Goodbye My Love",
    "Searchers - Needles And Pins",
    "Seekers - I ll Never Find Another You",
    "Semino Rossi - Rot sind die Rosen (deutsch)",
    "Shadows - Apache",
    "Shadows - Atlantis",
    "Shadows - Theme from the deer Hunter",
    "Shania Twain - Any Man Of Mine - Canadian Stomp - country",
    "Shania Twain - Whose Bed Have Your Boots Been Under",
    "Shannon Noll - We Only Live Once - We Only Live Once - country",
    "Sharif Dean - Do you love",
    "Shawn Elliot - Shame And Scandal In The Family",
    "Shocking Blue - Mighty Joe",
    "Shocking Blue - Venus",
    "Shuffles- Sha la la i need you - Albert West - 1970",
    "Sieneke - Eindeloos",
    "Sieneke - Lievelingsmelodie",
    "Sieneke - Wat n Ellende",
    "Simon  Garfunkel - The Boxer",
    "Simon & Garfunkel - Bridge Over Troubled Water",
    "Simon Garfunkel - El Condor Pasa",
    "Simon Garfunkel - The Boxer",
    "Sir Douglas Quintet - Mendocino",
    "Skeeter Davis - The End of the World",
    "Smokie - Living Next Door to Alice",
    "Sonny and Cher - Little Man",
    "Sparx - Todo Se Paga",
    "Spooky Sue - Swingin On A Star",
    "Spotnicks - Amapola",
    "St Bernard - Waltz",
    "Stampeders - Sweet City Woman",
    "Stealers Wheel - Stuck In The Middle With You",
    "Stefan van den Hout - Right here, right now - country",
    "Sugarland - It Happens - Rhyme Or Reason - country",
    "Supertramp - Give A Little Bit",
    "Surfers - Windsurfin",
    "Suzy Bogguss - Moment Of Truth - country",
    "Tavares - Heaven Must Be Missing An Angel",
    "Tee Set - Don t You Leave",
    "Tee Set - She Likes Weeds",
    "Terry Jacks - Seasons In The Sun",
    "Texas Tornados - Little Bit Is Better Than Nada - Better Than Nada - country",
    "The Bellamy Brothers - Let Your Love Flow",
    "The Black Devils - Without my love - country",
    "The Highwaymen - Against The Wind",
    "The Judds - Why Not Me",
    "The Last Bandoleros - Hey Baby Que Paso - country",
    "The Locomotions - Everynight - country",
    "The Mavericks - Dance In The Moonlight - country",
    "The Mavericks - La Mucara - Mucara Walk - country",
    "The Mavericks - Pizziricco - Pizziricco - country",
    "The Mavericks - The Losing Side Of Me - Winners & Losers - country",
    "The Mule Skinner Band - You Never Can Tell",
    "The Outlaws - The Best Part of the Day Is the Night - The Best Part of the Day - country",
    "The Overtones - Do You Love Me - Well Do Ya - country",
    "The Overtones - Don t Worry Be Happy - Be Happy Now - country",
    "The Overtones - Happy Days - Teenage Dreams - country",
    "The Overtones - Runaway - Runaway - country",
    "The Overtones - Who Put the Bomp - The Bomp - country",
    "The Script - Arms Open - Arms Open - country",
    "The Shuffles - Madelein - Albert West - 1969",
    "The Tielman Brothers - Donna",
    "The Tielman Brothers - Little Bird",
    "The Tielman Brothers - O Rosalie",
    "The Vamps - Oh Cecilia - Cecillia - country",
    "Theo van Cleeff - A Man Without Love",
    "Theo van Cleeff - Amigos Para Siempre",
    "Theo van Cleeff - Close My Eyes",
    "Theo van Cleeff - Don t Cry",
    "Theo van Cleeff - Heel mijn leven met jou",
    "Theo van Cleeff - Hold Me in Your Arms",
    "Theo van Cleeff - I,ll keep dreaming off you - country",
    "Theo van Cleeff - I,ll keep dreaming off you",
    "Theo van Cleeff - Sancta Maria",
    "Three Degrees - Dirty Ol Man",
    "Tim Culpepper - Its Friday Night - Its Friday Night - country",
    "Tim Hardin - How Can We Hang On To A Dream",
    "Tim Tim - Under The Sun - Under The Sun - country",
    "Tina Turner - Proud Mary",
    "Tino Martin - Het Is Goed Zo",
    "Tino Martin - Jij Liet Mij Vallen",
    "Tino Martin - Toch zal ik altijd aan je denken",
    "Toby Keith - Cabo San Lucas - Pacifico - country",
    "Toby Keith - Thunderbird - country",
    "Tokens - The Lion Sleeps Tonight",
    "Tol & Tol - Eleni",
    "Tol & Tol - Take Me Home - Homeward Bound - country",
    "Tol & Tol - Take Me Home",
    "Tom Dick - Bloody Mary",
    "Tom Jones - Delilah",
    "Tom Jones - Green green grass of home",
    "Tom Jones - I ll Never Fall In Love Again",
    "Tommy Steib - Irgendwann muas a jeder moi gehn",
    "Tony Bass - Dat Is T Einde",
    "Tony Bass - Gina Lollobrigida",
    "Tony Christie - Is This The Way To Amarillo",
    "Tony Christie - Knocking On Your Door",
    "Tony Orlando Dawn - Tie A Yellow Ribbon Round The Old Oak Tree",
    "Tony Renis - Quando, Quando, Quando",
    "Toto - Africa",
    "Toto - Rosanna",
    "Touch Of Class - Mexican Girl - country",
    "Traveling Wilburys - End Of The Line",
    "Traveling Wilburys - Handle With Care",
    "Travis Tritt - Southbound Train - country",
    "Tremeloes - My little Lady",
    "Tremeloes - Silence Is Golden",
    "Tremeloes-Silence Is Golden",
    "Trio Hellenique - Dans van Zorba ( Sirtaki ) ( 1965 )",
    "Troggs - With a girl like you",
    "Tumbleweeds - Somewhere Between - country",
    "Tumbleweeds - Somewhere Between",
    "Turtles - Happy Together",
    "Twist - Lets Twist again",
    "UB40 - Red Red Wine",
    "Van Morrison - Brown Eyed Girl",
    "Vanessa Hudgens - Can I Have This Dance - Take My Hand - country",
    "Vicky Leandros - Apres toi",
    "Vicky Leandros - Ich Hab Die Liebe Gesehn",
    "Village People - YMCA",
    "Vince Gill - I Never Really Knew You - All Those Little Lies - country",
    "VogtlandCowboy - Speak To The Sky - Speak To The Sky - country",
    "Walkers - Oh Lonesome Me",
    "Wanda Jackson - Santo Domingo",
    "Who - See Me, Feel Me",
    "Will Tura - Hemelsblauw",
    "Willie Nelson - On The Road Again",
    "Willy Sommers - Laat De Zon In Je Hart",
    "Wim Sonneveld - Het Dorp",
    "ZZ en de Maskers - La Comparsa",
    "Zager Evans - In the Year 2525",
    "Zen - Hair",
    "Zingende Amateur - Ouwe Orgelman",
    "Zonzo Basily - Proost met mij",
    "Zorba - Sirtaki - Sirtaki - country"
];